### ISSUE TITLE
Use input tensor's device in some utils_fns, rather than utils_fns.device? 

### ISSUE THREAD

**Issue by jordansauce** [callummcdougall/sae_vis#11]
Hi Callum! 
I'm looking at integrating your feature visualization tools into some of our SAE code with Apollo (primarily [@danbraunai-apollo](https://github.com/danbraunai-apollo) and [@Stefan-Heimersheim](https://github.com/Stefan-Heimersheim)). Is this cool with you? If so, how do you feel about us potentially contributing to this codebase, or forking it? (we can set up a meeting to discuss if you have time)

For now, I'm using some classes in `utils_fns.py` (`TopK` and `QuantileCalculator`), and I notice that they error when the device of the input tensor is not equal to `utils_fns.device`. I'm thinking it might be nice for these functions to base their device on the input tensors, while preserving functionality in the case where the input tensors are on that device. I would have submitted a PR but I don't have access:
Code: [utils_fns.zip](https://github.com/callummcdougall/sae_vis/files/14488120/utils_fns.zip)
![image](https://github.com/callummcdougall/sae_vis/assets/52150832/d77ef6b8-4a21-4dee-8bee-6195c1fdb9a8)

**Comment by callummcdougall** [comment]
Yep, thanks for noting this - I'll make this edit, and push it the next time I update the library (possibly tomorrow)
