### ISSUE TITLE
I'd like to see correlated features for the same SAE. 

### ISSUE THREAD

**Issue by jbloomAus** [callummcdougall/sae_vis#21]
I think it would be good to generated top correlated features in the SAME SAE rather than for a second one (or have this option). 

Code here (https://github.com/callummcdougall/sae_vis/blob/9b573b27590db1cbd6c8ef08fca7ff8c9d26b340/sae_vis/data_fetching_fns.py#L224) suggests we only calculate correlated features for another SAE.

**Comment by callummcdougall** [comment]
Done! I've attached a screenshot of the output, as well as the new config params associated with the feature tables data. I've also started a version log, which will help keep track of the changes that have been made to the repo.

<img src="https://github.com/callummcdougall/sae_vis/assets/45238458/302fe56a-95a8-4668-ac40-87a782ad2fa7" width="550">

<img src="https://github.com/callummcdougall/sae_vis/assets/45238458/b268a3b3-7e31-434b-a4bc-282fb7295f00" width="300">
