### ISSUE TITLE
Circular dependency between SAELens and sae_vis

### ISSUE THREAD

**Issue by chanind** [callummcdougall/sae_vis#42]
sae_vis depends on SAELens in dependencies, but SAELens also depends on sae_vis. This doesn't seem like a stable situation and is likely to cause issues.

It looks like the SAELens depedency in sae_vis is only there for the [demo.ipynb](https://github.com/callummcdougall/sae_vis/blob/4e7a24c37444f11d718035eede68ac728d949a20/demo.ipynb). Since this isn't a core dependency, I would recommend removing it from the main dependency list.

One option is to create and `extras` group called `demo` or something similar, so that it's possible to install `pip install sae-vis[demo]` for the demo requirements, but these won't be installed by default. More info on extras is here: https://python-poetry.org/docs/pyproject/#extras

Another possible solution is to just add `!pip install sae-lens` to the top of the demo.ipynb file, so the dependency is self-contained there.

**Comment by hijohnnylin** [comment]
+1 support either solution. maybe slightly prefer the `!pip install sae-lens` so that folks dont need to jump out of the notebook to do something special

**Comment by callummcdougall** [comment]
I'm happy with the latter (the pip install approach is how most of my tutorials work). Would someone mind making this as a PR?
