### ISSUE TITLE
Bug in calculation of encoder B forward pass when calculating correlation coefficients

### ISSUE THREAD

**Issue by jbloomAus** [callummcdougall/sae_vis#45]
https://github.com/callummcdougall/sae_vis/blob/034eefa5a4163e9a560b574e2e255cd06f8f49a1/sae_vis/data_fetching_fns.py#L119C1-L119C62

`feat_acts_B = F.relu(feat_acts_pre_B + encoder.b_enc)` -> `feat_acts_B = F.relu(feat_acts_pre_B + encoder_B.b_enc)`

The wrong encoder bias was being used in the calculation of feature activations.

**Comment by callummcdougall** [comment]
*facepalms* thanks!
