### ISSUE TITLE
Proposal: change colour handling code to scale with the max activation in a prompt.

### ISSUE THREAD

**Issue by ArthurConmy** [callummcdougall/sae_vis#9]
Currently, the background color logic sets all activations>1 to the maximally orange colour like so:

https://github.com/callummcdougall/sae_vis/blob/2740c0047e78df7e56d7bcf707c909ac18e71c1f/sae_vis/html_fns.py#L156-L157

Wouldn't scaling the colours from 0 to the max activation in a prompt be generally better? Specifically, scale the `feat_acts` by 

```python
bg_values = np.maximum(feat_acts, 0) / max(1, np.max(feat_acts))
```

...so that we don't apply scaling to the cases where the max activation in the prompt is less than 1.0, which would be distracting as well as error when nothing fires in the prompt.

**Comment by callummcdougall** [comment]
Yep, this seems v reasonable, I'll add this to the list of planned sae-vis changes (got a few fun ones planned on the flight back this weekend!)

**Comment by callummcdougall** [comment]
Done (on next push)
